# src/feature_extraction/config.yml

# Config for feature extraction

data:
  videos_dir: "/path/to/videos"
  angles_dir: "/path/to/angles_csvs"
  output_dir: "/path/to/output"
  images_subdir: "images"  # Folder for images

parameters:
  threshold: 30.0
  contamination: 0.05

logging:
  log_level: "INFO"  # log level (DEBUG, INFO, WARNING, ERROR)
